version: 0.0
os: linux
files:
  - source: /
    destination: /home/bagisto/bagisto/public
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/create_test_db.sh
      timeout: 30
      runas: root
    - location: scripts/create_test_db.sh
      timeout: 30
      runas: root
    - location: scripts/apache2.sh
      timeout: 30
      runas: root
    - location: scripts/php_ini.sh
      timeout: 30
      runas: root
    - location: scripts/site.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/install_composer_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/useradd.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
    - location: scripts/permission.sh
      timeout: 30
      runas: root
