version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/public
    overwrite: true
hooks:
  AfterInstall:
    - location: scripts/permission.sh
      timeout: 30
      runas: root
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
